### ISSUE TITLE
2022-11-05_0341 - JeffreyBodin - TheCodeForge-syzitus - issue #secFlaw #secFinancial #secFiduciaries #user-experience-pipelines

### ISSUE THREAD

**Issue by JeffreyBodin** [TheCodeForge/syzitus#3]
2022-11-05_0341 - JeffreyBodin - TheCodeForge-syzitus - issue #secFlaw #secFinancial #secFiduciaries #user-experience-pipelines

-----

// Post | `+Porpl` "guild"
➡ https://syzitus.com/+Porpl/post/14/treason
➡ https://i.imgur.com/DOtK8jq.png
      ![ ](https://i.imgur.com/DOtK8jq.png)

// URL | my comment reply
➡ https://syzitus.com/+Porpl/post/14/treason/3o
      ![ ](https://i.imgur.com/uZ3wvtO.png)

// Source | my comment reply
```
Nope. But, here's a ![briefcase](https://i.imgur.com/q3xD2oP.jpeg) full of cash to fund your acquisitions. 

As any prpl blooded patriot knows defensibility is in *all* our **interests**.

No, the cash is ofc not marked. Purely investiture into **ourselves**. Not at all insured by our internal fed boi surveillance.
```

-----

Issue is noted
  Subversion of financial user-experience pipelines (preservation or peril) (presumed) current

Fiduciaries dateOf 
  Presumedly 
    *current*
    && 
    **enforced**
  (2022-11-05_0349)

Ie 
  user's --> Settings => Premium === 'Direct image uploads in comments'
  ||
  https://syzitus.com/settings/profile

Citation
➡ https://i.imgur.com/hdF4CJQ.png
      ![ ](https://i.imgur.com/hdF4CJQ.png)

**Comment by TheCodeForge** [comment]
I have no idea what you're trying to say
