### ISSUE TITLE
[question] pyrena repo - abandoned or broken link? - willing to contribute

### ISSUE THREAD

**Issue by alicecommits** [TheCodeForge/syzitus#9]
Hello,
Sorry for dropping it as an Issue here, but I couldn't find your contact details or the repo I'm looking for, and you seem to commit actively to this one.

I've just discovered your package pyrena for Arena PLM REST API:
https://pypi.org/project/pyrena/
https://libraries.io/github/TheCodeForge/pyrena

I'm also writing a pyrena library, because my company uses Arena PLM as well, with a lot of the logics overlapping with yours. For my library, I thought of some enhancements in the request shaping, object searching and retrieving.
My library is also based on requests.

Therefore I wanted to know if the project and repo still existed, and if so, if you'd be interested in me contributing?
I read on pypi.org that the repo link was: 
https://github.com/thecodeforge/pyrena
However the link seems broken.

Thanks in advance for your feedback
Have a nice day,

**Comment by TheCodeForge** [comment]
Unprivated Pyrena. Contributions would be welcome, thank you for your interest.
